### ISSUE TITLE
RuntimerError: expected scalar type Float but found Double

### ISSUE THREAD

**Issue by mengW6** [XingliangJin/MCM-LDM#5] opened 2024-07-11 12:46 UTC
Hello, I encountered this error while running the demo. Do you know how to solve it?
The command line to run is as follows:
python demo_transfer.py --cfg ./configs/config_mld_humanml3d.yaml --cfg_assets ./configs/assets.yaml --style_motion_dir demo/style_motion --content_motion_dir demo/content_motion --scale 2.5

<img width="519" alt="图片1" src="https://github.com/XingliangJin/MCM-LDM/assets/147932983/a197956a-4ce9-46f3-ae04-ac2f06f49ba0">

**Comment by XingliangJin** [comment] 2024-07-11 13:08
Seems like there is data type error, I can't reproduce this error. You can try to use `trans_cond = trans_cond.to(torch.float32)` befor [this line](https://github.com/XingliangJin/MCM-LDM/blob/8724ee36d4b23ccbbcffac6151a11467d883480a/mld/models/architectures/mld_denoiser.py#L248C40-L248C50).

**Comment by mengW6** [comment] 2024-07-11 15:05
Now there is another problem, as shown in the picture below. Can you give me some guidance?
Also, may I ask if the version number of matplotlib must be version 3.1.3?  I am using version 3.8.4.
<img width="748" alt="图片2" src="https://github.com/XingliangJin/MCM-LDM/assets/147932983/9a4e2caa-4836-4a5c-a6ad-891282d613e7">

**Comment by XingliangJin** [comment] 2024-07-11 15:14
Yes, this is because the version of the matplotlib is too high. 3.1.3 is fine, you can also try other low versions.

**Comment by mengW6** [comment] 2024-07-12 05:58
1、May I ask where the content_mation and style_motion in the demo come from and how they were obtained?
2、 I want to use your model and method to generate trajectory and style controlled dances based on music ，can the Multi condition Motion Latent Diffusion Model network adapt to such inputs（The following figure）? Do you think it can be achieved ? If you could give me some advice, that would be very grateful.
<img width="608" alt="图片1" src="https://github.com/user-attachments/assets/54f1fe7e-f013-4ad1-b06a-5a6df0189c5b">

**Comment by XingliangJin** [comment] 2024-07-12 06:29
1. The input motion is 263-dim format data from the HumanML3D dataset (in the new_joint_vecs floder). If you have your customed SMLP-based motion, you can use the processing code in [HumanML3D](https://github.com/EricGuo5513/HumanML3D) to get 263-dim format motion.
2. Our trajectory condition is used to make the transferred motion's trajectory to fit the original content motion and meanwhile avoid footsliding issue. So it mast be extracted from content motion. Of course, we have also tried to use other trajectories to control the generated motion to produce different trajectories. But the results are not good. 
3. It is a good idea to transfer the style to the dance sequences. In fact, there are many dance sequences in HumanML3D. I suggest you can try it.

**Closed as completed** 2024-07-23 12:35 UTC
